# Generated by Django 5.2.13 on 2026-06-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app_project", "0002_alter_patientprosthesis_doctor_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="amputation_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Udo", "Udo"),
                    ("Podudzie", "Podudzie"),
                    ("Staw biodrowy", "Staw biodrowy"),
                    ("Ramię", "Ramię"),
                    ("Przedramię", "Przedramię"),
                    ("Dłoń", "Dłoń"),
                ],
                max_length=50,
                null=True,
                verbose_name="Poziom amputacji",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="circumference",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Obwód kikuta (cm)"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="limb_type",
            field=models.CharField(
                blank=True,
                choices=[("Noga", "Noga"), ("Ręka", "Ręka")],
                max_length=10,
                null=True,
                verbose_name="Amputowana kończyna",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("Lewa", "Lewa"), ("Prawa", "Prawa")],
                max_length=10,
                null=True,
                verbose_name="Strona amputacji",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("S", "S"), ("M", "M"), ("L", "L")],
                max_length=2,
                null=True,
                verbose_name="Rozmiar (obliczony)",
            ),
        ),
        migrations.AddField(
            model_name="prosthesis",
            name="amputation_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Udo", "Udo"),
                    ("Podudzie", "Podudzie"),
                    ("Staw biodrowy", "Staw biodrowy"),
                    ("Ramię", "Ramię"),
                    ("Przedramię", "Przedramię"),
                    ("Dłoń", "Dłoń"),
                ],
                max_length=50,
                null=True,
                verbose_name="Poziom amputacji/protezy",
            ),
        ),
        migrations.AddField(
            model_name="prosthesis",
            name="limb_type",
            field=models.CharField(
                blank=True,
                choices=[("Noga", "Noga"), ("Ręka", "Ręka")],
                max_length=10,
                null=True,
                verbose_name="Typ kończyny",
            ),
        ),
        migrations.AddField(
            model_name="prosthesis",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("Lewa", "Lewa"), ("Prawa", "Prawa")],
                max_length=10,
                null=True,
                verbose_name="Strona",
            ),
        ),
        migrations.AddField(
            model_name="prosthesis",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("S", "S"), ("M", "M"), ("L", "L")],
                max_length=2,
                null=True,
                verbose_name="Rozmiar leja",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nazwa firmy"),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nazwa parametru"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="budget",
            field=models.FloatField(verbose_name="Budżet (zł)"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Imię"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Nazwisko"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="prostheses",
            field=models.ManyToManyField(
                blank=True,
                through="web_app_project.PatientProsthesis",
                to="web_app_project.prosthesis",
                verbose_name="Zapisane protezy",
            ),
        ),
        migrations.AlterField(
            model_name="patientprosthesis",
            name="doctor_notes",
            field=models.TextField(blank=True, verbose_name="Notatki lekarza"),
        ),
        migrations.AlterField(
            model_name="patientprosthesis",
            name="match_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Wynik dopasowania (%)"
            ),
        ),
        migrations.AlterField(
            model_name="patientprosthesis",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="web_app_project.patient",
                verbose_name="Pacjent",
            ),
        ),
        migrations.AlterField(
            model_name="patientprosthesis",
            name="prosthesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="web_app_project.prosthesis",
                verbose_name="Proteza",
            ),
        ),
        migrations.AlterField(
            model_name="prosthesis",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="web_app_project.company",
                verbose_name="Firma",
            ),
        ),
        migrations.AlterField(
            model_name="prosthesis",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nazwa protezy"),
        ),
        migrations.AlterField(
            model_name="prosthesis",
            name="parameters",
            field=models.ManyToManyField(
                through="web_app_project.ProsthesisParameter",
                to="web_app_project.parameter",
                verbose_name="Parametry",
            ),
        ),
        migrations.AlterField(
            model_name="prosthesis",
            name="price",
            field=models.FloatField(verbose_name="Cena (zł)"),
        ),
        migrations.AlterField(
            model_name="prosthesisparameter",
            name="value",
            field=models.CharField(max_length=200, verbose_name="Wartość"),
        ),
    ]
