# Generated by Django 5.2.13 on 2026-06-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_app_project",
            "0003_patient_amputation_level_patient_circumference_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prosthesis",
            name="parameters",
        ),
        migrations.RemoveField(
            model_name="prosthesisparameter",
            name="parameter",
        ),
        migrations.RemoveField(
            model_name="prosthesisparameter",
            name="prosthesis",
        ),
        migrations.DeleteModel(
            name="Parameter",
        ),
        migrations.DeleteModel(
            name="ProsthesisParameter",
        ),
    ]
